default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: titleless_development

test:
  <<: *default
  database: titleless_test

production:
  <<: *default
  database: titleless_production
  username: titleless
  password: <%= ENV['TITLELESS_DATABASE_PASSWORD'] %>
